# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Immersive
email: pganme@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A simple blog for who likes technology.
  
  
baseurl: "/immersive" # the subpath of your site, e.g. /blog
url: http://imersive.tech

#sidebar
default-image: logo_big_thumb.jpg # If there is no featured image in a post then this image will be showed. Also on all pages this image will be showed. Use a 500x250 image.

#footer

built-by: Ganme Corp

copyright:
   name: Immersive
   link: 'http://imersive.tech'

# Build settings
markdown: kramdown
permalink: /:title/
paginate: 6
paginate_path: /page:num/

# Tracker
analytics: 

# Comments
disqus: yes
disqus-shortname: imersivetech

#social

twitter: https://twitter.com/PMASTUDIO_WEB
github: https://github.com/PMASTUDIO/
email: pganme@gmail.com

# Sass style
sass:
  style: compressed

# Ruby Gems
plugins: [jekyll-paginate, jekyll-seo-tag]

